language: php
 
php:
 - 7.0
 
branches:
 - master

before_script:
 - mkdir -p plugins/Apollo
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
 - chmod +x travis.sh
 
script:
 - ./travis.sh

notifications:
 email: false
